services:
  - type: web
    name: hospital-queue
    env: docker
    dockerfilePath: Dockerfile
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: staging
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://hospital-queue-frontend-a6wc.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-queue-db-staging
          property: connectionString

databases:
  - name: hospital-queue-db-staging
    databaseName: hospital_queue
    user: hospital_user
    plan: free